#!/bin/sh
# create a package list for every docker image in a "packages" directory

mkdir -p packages

# Debian based base images
docker run --entrypoint "" --rm debian:buster-slim dpkg -l > packages/debian_buster
docker run --entrypoint "" --rm ehlers/ipterm dpkg -l > packages/ipterm
docker run --entrypoint "" --rm ehlers/webterm dpkg -l > packages/webterm
# docker run --entrypoint "" --rm ehlers/web_java dpkg -l > packages/web_java

# Debian based images
grep -ilE '^FROM .*\b(debian|ipterm|webterm)' */Dockerfile | while read -r dockerfile; do
        image=$(dirname "$dockerfile")
	docker run --entrypoint "" --rm $image dpkg -l > packages/$image
done

# Alpine base image
docker run --entrypoint "" --rm alpine apk list -q -I | sort > packages/alpine

# Alpine based images
grep -il '^FROM alpine' */Dockerfile | while read -r dockerfile; do
        image=$(dirname "$dockerfile")
	docker run --entrypoint "" --rm $image apk list -q -I | sort > packages/$image
done
